---
- name: enable perl
  hosts: all
  gather_facts: true

  tasks:
    - name: add perl on RHEL 8
      ansible.builtin.dnf:
        name: '@perl:5.26'
        state: present
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "8"

...
