---
- name: generic setup up playbook
  hosts: all
  gather_facts: true

  tasks:
    - name: gather facts
      ansible.builtin.setup:
      register: results

    - name: display the facts
      ansible.builtin.debug:
        var: results
...
